= Profile Privilege Mode

RISC-V has a layered architecture supporting multiple privilege modes,
and most RISC-V platforms support more than one privilege mode.
Software is usually written assuming a particular privilege mode
during execution.  For example, application code is written assuming
it will be run in user mode, and kernel code is written assuming it
will be run in supervisor mode.

NOTE: Software can be run in a mode different than the one for which
it was written. For example, privileged code using privileged ISA
features can be run in a user-mode execution environment, but will
then cause traps into the enclosing execution environment when
privileged instructions are executed.  This behavior might be
exploited, for example, to emulate a privileged execution environment
using a user-mode execution environment.

The profile for a privilege mode describes the ISA features for an
execution environment that has the eponymous privilege mode as the
most-privileged mode available, but also includes all supported
lower-privilege modes.  In general, available instructions vary by
privilege mode, and the behavior of RISC-V instructions can depend on
the current privilege mode.  For example, an S-mode profile includes
U-mode as well as S-mode and describes the behavior of instructions
when running in different modes in an S-mode execution environment,
such as how an `ecall` instruction in U-mode causes a contained trap
into an S-mode handler whereas an `ecall` in S-mode causes a requested
trap out to the execution environment.

A profile may specify that certain conditions will cause a requested
trap (such as an `ecall` made in the highest-supported privilege mode)
or fatal trap to the enclosing execution environment.  The profile
does not specify the behavior of the enclosing execution environment
in handling requested or fatal traps.

NOTE: In particular, a profile does not specify the set of ECALLs
available in the outer execution environment.  This should be
documented in the appropriate binary interface to the outer execution
environment (e.g., Linux user ABI, or RISC-V SEE).

NOTE: In general, a profile can be implemented by an execution
environment using any hardware or software technique that provides
compatible functionality, including pure software emulation.

A profile does not specify any invisible traps.

NOTE: In particular, a profile does not constrain how invisible traps
to a more-privileged mode can be used to emulate profile features.

A more-privileged profile can always support running software to
implement a less-privileged profile from the same profile family.  For
example, a platform supporting the S-mode profile can run a
supervisor-mode operating system that provides user-mode execution
environments supporting the U-mode profile.

NOTE: Instructions in a U-mode profile, which are all executed in user
mode, have potentially different behaviors than instructions executed
in user mode in an S-mode profile.  For this reason, a U-mode profile
cannot be considered a subset of an S-mode profile.
